### ISSUE TITLE
TypeError: undefined is not a function when building

### ISSUE THREAD

**Issue by fbjerggaard** [kasperisager/vanilla-bootstrap#177]
I am getting the above error when running either `npm run build` or `npm run watch` 

This is the output of `npm run build`:

    > vanilla-bootstrap@ build D:\code\bootstrap
    > gulp
    
    [20:55:05] Using gulpfile D:\code\bootstrap\gulpfile.js
    [20:55:05] Starting 'styles'...
    [20:55:06] 'styles' errored after 799 ms
    [20:55:06] TypeError: undefined is not a function
        at Gulp.<anonymous> (D:\code\bootstrap\gulpfile.js:23:18)
        at module.exports (D:\code\bootstrap\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
        at Gulp.Orchestrator._runTask (D:\code\bootstrap\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
        at Gulp.Orchestrator._runStep (D:\code\bootstrap\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
        at Gulp.Orchestrator.start (D:\code\bootstrap\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
        at D:\code\bootstrap\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:355:11)
        at Function.Module.runMain (module.js:503:11)
        at startup (node.js:129:16)
        at node.js:814:3

        npm ERR! Windows_NT 6.3.9600
        npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program         Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
        npm ERR! node v0.12.7
        npm ERR! npm  v2.11.3
        npm ERR! code ELIFECYCLE
        npm ERR! vanilla-bootstrap@ build: `gulp`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the vanilla-bootstrap@ build script 'gulp'.
        npm ERR! This is most likely a problem with the vanilla-bootstrap package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     gulp
        npm ERR! You can get their info via:
        npm ERR!     npm owner ls vanilla-bootstrap
        npm ERR! There is likely additional logging output above.

**Comment by fbjerggaard** [comment]
This happens on both Windows and Linux node.js 0.12.7 from a fresh install.

**Comment by fbjerggaard** [comment]
@kasperisager - Building works fine, the watch command however still gives me the same error.
